version: '3.9'
services: 
  dumper:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8001:8001"
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on: 
      - dumper